"""create games table

Revision ID: d416a9948fc0
Revises: 
Create Date: 2026-07-04 04:00:55.795908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd416a9948fc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('player_color', sa.Enum('WHITE', 'BLACK', name='playercolor'), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('computer_max_depth', sa.Integer(), nullable=False),
    sa.Column('computer_algorithm', sa.Enum('NAIVE_MINIMAX', name='searchalgorithm'), nullable=False),
    sa.Column('computer_evaluator', sa.Enum('SHANNON', name='evalfunction'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'CHECKMATE', 'STALEMATE', 'DRAW', 'RESIGNED', 'ABANDONED', name='gamestatus'), nullable=False),
    sa.Column('moves', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('time_started', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_session_id'), 'games', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_session_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
